version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git clone https://github.com/ItsVixano/android_kernel_xiaomi_daisy --single-branch --depth=1 daisy
           cd daisy
           bash lineage.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
